In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn.cluster as cluster

In [52]:
data = pd.read_csv('../datasets/Online_Retail.csv', encoding='latin1')

In [53]:
df = pd.DataFrame(data)

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [54]:
# drop unwanted columns if they exist
df.drop(['InvoiceNo', 'StockCode', 'Description', 'InvoiceDate', 'CustomerID'],
    axis=1, errors='ignore', inplace=True)

df.head()

   Quantity  UnitPrice         Country
0         6       2.55  United Kingdom
1         6       3.39  United Kingdom
2         8       2.75  United Kingdom
3         6       3.39  United Kingdom
4         6       3.39  United Kingdom

In [55]:
X = df[['Quantity', 'UnitPrice']]
y = df['Country']

In [56]:
# Encode Country in the same dataframe
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Country'] = le.fit_transform(df['Country'])

df.head()

   Quantity  UnitPrice  Country
0         6       2.55       36
1         6       3.39       36
2         8       2.75       36
3         6       3.39       36
4         6       3.39       36

In [62]:
df = pd.get_dummies(df)
df.corr()

           Quantity  UnitPrice   Country
Quantity   1.000000  -0.001235 -0.012056
UnitPrice -0.001235   1.000000 -0.001491
Country   -0.012056  -0.001491  1.000000